name: Continuous Deployment

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build
        run: |
          npm install
          npm run build
        env:
          REACT_APP_ENV: ${{ secrets.REACT_APP_ENV }}
          REACT_APP_API_HOST: ${{ secrets.REACT_APP_API_HOST }}
          REACT_APP_PERSIST_STORE_ENCRYPTION_KEY: ${{ secrets.REACT_APP_PERSIST_STORE_ENCRYPTION_KEY }}
          REACT_APP_PERSIST_CONFIG_SECRET: ${{ secrets.REACT_APP_PERSIST_CONFIG_SECRET }}

      - name: Upload Artifacts 🔺 # The project is then uploaded as an artifact named 'site'.
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: build

  deploy:
    name: Deploy
    concurrency: ci-${{ github.ref }}
    needs: [build] # The second job must depend on the first one to complete before running and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Download Artifacts 🔻 # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v1
        with:
          name: site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          folder: 'site' # The deployment folder should match the name of the artifact. Even though our project builds into the 'build' folder the artifact name of 'site' must be placed here.

      # - name: Build & Deploy React app to GitHub Pages
      #   uses: MrKrishnaAgarwal/deploy-react-app-to-gh-pages@v1.0.0

  #     - name: Compress action step
  #       uses: a7ul/tar-action@v1.1.0
  #       id: compress
  #       with:
  #         command: c
  #         files: |
  #           ./build
  #         outPath: github-pages.tar.gz

  #     - name: Upload GitHub Pages artifact
  #       uses: actions/upload-pages-artifact@v1.0.3
  #       with:
  #         path: ./

  # deploy:

  #   needs: build

  #   name: Deploy

  #   # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  #   permissions:
  #     pages: write      # to deploy to Pages
  #     id-token: write   # to verify the deployment originates from an appropriate source

  #   # Deploy to the github-pages environment
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   # Specify runner + deployment step
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1
  #       with:
  #         token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
